apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: devsecops-oai
  namespace: cicd
spec:
  pipelineRef:
    name: devsecops-oai
  workspaces:
  - name: workspace
    persistentVolumeClaim:
      claimName: devsecops-workspace
